name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y build-essential
        shell: bash

      - name: Install GCC (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install mingw -y
        shell: bash

      - name: Build project
        run: make all
        shell: bash

      - name: Run tests
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            test/test.exe
          else
            ./test/test
          fi
        shell: bash

      - name: Clean build
        run: make clean
        shell: bash
